# Generated by Django 4.2.2 on 2023-09-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='desc',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
