# Generated by Django 4.2.2 on 2023-09-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailapp', '0002_alter_course_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
