# Generated by Django 4.2.2 on 2023-09-20 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detailapp', '0003_alter_course_desc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('dep_name',)},
        ),
    ]
