# Generated by Django 4.2.2 on 2023-09-20 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detailapp', '0004_alter_course_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
    ]
