# Generated by Django 4.2.2 on 2023-09-21 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detailapp', '0006_contactquery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactquery',
            old_name='phone_no',
            new_name='phonenumber',
        ),
    ]
