# Generated by Django 4.2.2 on 2023-09-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailapp', '0007_rename_phone_no_contactquery_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactquery',
            name='phonenumber',
            field=models.IntegerField(),
        ),
    ]
