# Generated by Django 4.2.2 on 2023-09-21 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detailapp', '0008_alter_contactquery_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactquery',
            old_name='phonenumber',
            new_name='phone_number',
        ),
    ]
