# Generated by Django 4.2.2 on 2023-09-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailapp', '0009_rename_phonenumber_contactquery_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactquery',
            name='phone_number',
            field=models.TextField(),
        ),
    ]
